/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.22
 * Generated at: 2016-10-01 19:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import yoon.member.model.MemberDTO;

public final class joinOk_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/join/../menu.jsp", Long.valueOf(1475160912000L));
    _jspx_dependants.put("/join/../navbar.jsp", Long.valueOf(1475026517000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("yoon.member.model.MemberDTO");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"margin: 0px;\" bgcolor=\"transparent\">\r\n");
      out.write("\t<div id=\"wrapper\"> \r\n");
      out.write("\t<!-- top line-->\r\n");
      out.write("\t\t<div class='roof' style=\"width:100%; height:0px; margin:0; padding:0;\"></div>\r\n");
      out.write("\t\t<!-- top line-->\r\n");
      out.write("\t\t<!-- wrapper -->\r\n");
      out.write("\t\t<div class='center-wrapper' style=\"width:1000px; margin:0 auto;\">\r\n");
      out.write("\t\t<!-- header-->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>\r\n");
      out.write("\r\n");
      out.write("\t<link href='https://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t<script type='text/javascript' src='js/jquery-3.1.0.min.js'></script>\r\n");
      out.write("\t<script type='text/javascript' src='js/additional-methods.min.js'></script>\r\n");
      out.write("\t<script type='text/javascript' src='js/jquery.validate.min.js'></script>\r\n");
      out.write("\t<script type='text/javascript' src='js/messages_ko.min.js'></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/rsa/jsbn.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/rsa/rsa.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/rsa/prng4.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/rsa/rng.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-filestyle.js\"></script>\r\n");
      out.write("\t<link href=\"css/base.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"css/jquery-filestyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background-color: #3A3B3D;\r\n");
      out.write("    border:0px;\r\n");
      out.write("}\r\n");
      out.write("li {\r\n");
      out.write("    float: right;\r\n");
      out.write("}\r\n");
      out.write("li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 5px 16px;\r\n");
      out.write("    font-family:Misaeng;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size:20px;\r\n");
      out.write("    font-family:Misaeng;\r\n");
      out.write("}\r\n");
      out.write("li a:hover {\r\n");
      out.write("    background-color: #111;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class='navbar'>\r\n");

	MemberDTO mbdto = (MemberDTO)session.getAttribute("loginOkUser");
 	String pic = "img/default_profile.png";
 	
	if(mbdto == null){

      out.write("\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t  <li><a href=\"member.do?method=joinform\">회원가입</a></li>\r\n");
      out.write("\t  <li><a href=\"member.do?method=loginform\">로그인</a></li>\r\n");
      out.write("\t</ul>\r\n");

	}else{
		if(mbdto.getPic() == null){
			mbdto.setPic(pic);
		}

      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("  <li><a id=\"btn_logout\">로그아웃</a></li>\r\n");
      out.write("  <li><a href=\"member.do?method=mypage\">");
      out.print( mbdto.getName() );
      out.write("님</a></li>\r\n");
      out.write("  <li><a href=\"member.do?method=mypic\"><img src =\"");
      out.print(mbdto.getPic());
      out.write("\" width=\"25px\" height=\"25px\"></a></li>\r\n");
      out.write("</ul>\r\n");

	}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#btn_logout\").click(function(){\r\n");
      out.write("\t\tvar result = confirm(\"로그아웃 하시겠습니까?\");\r\n");
      out.write("\t\tif(result){\r\n");
      out.write("\t\t\tlocation.replace(\"member.do?method=logout\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class='center-header'>\r\n");
      out.write("<b id=\"r_title\" style=\"font-size:65px;\">쉬어가기. . .</b><br>\r\n");
      out.write("<b id=\"r_title\" style=\"font-size:40px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      생각이 고이는 시간</b>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<table width=\"1000\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<table id=\"menu-table\" width='100%' >\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"main.do\" id=\"menu1\" class=\"a_text\">메인화면</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"main.do?method=list\" id=\"menu3\" class=\"a_text\">질문리스트</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"qget.do?method=list&pg=1\" id=\"menu4\" class=\"a_text\">질문제보</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"board.do?method=list&pg=1\" id=\"menu2\" class=\"a_text\">일상 게시판</a></td>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr width=\"90%\" color=\"white\" noshade>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('#menu1').mouseenter(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu1').mousedown(function(){\r\n");
      out.write("\t\t$(this).css('color','#505050');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu1').mouseleave(function(){\r\n");
      out.write("\t\t$(this).css('color','white');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu1').mouseup(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu2').mouseenter(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu2').mousedown(function(){\r\n");
      out.write("\t\t$(this).css('color','#505050');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu2').mouseleave(function(){\r\n");
      out.write("\t\t$(this).css('color','white');\r\n");
      out.write("\t})\t\r\n");
      out.write("\t$('#menu2').mouseup(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu3').mouseenter(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu3').mousedown(function(){\r\n");
      out.write("\t\t$(this).css('color','#505050');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu3').mouseleave(function(){\r\n");
      out.write("\t\t$(this).css('color','white');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu3').mouseup(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu4').mouseenter(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu4').mousedown(function(){\r\n");
      out.write("\t\t$(this).css('color','#505050');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu4').mouseleave(function(){\r\n");
      out.write("\t\t$(this).css('color','white');\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#menu4').mouseup(function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t  <p id=\"board_title\"><br><br>\r\n");

	String check = (String)request.getAttribute("check");
	if(check == null){

      out.write("\t\t  \r\n");
      out.write("\t\t 회원가입에 성공하셨습니다!!!<br><br></p>\r\n");
      out.write("\t\t<hr width=\"90%\" color=\"White\" noshade><br><br><br>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t<a href=\"member.do?method=loginform\" id=\"go_login\" style=\"font-family:Dokdo;font-size:30px;\">로그인하기</a>\r\n");
      out.write("\t\t</div>\r\n");

	}else{

      out.write("\r\n");
      out.write("\t\t회원가입 실패! 다시 시도해주세요.\r\n");
      out.write("\t\t<hr width=\"90%\" color=\"White\" noshade><br><br><br>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t<a href=\"member.do?method=loginform\" id=\"go_login\" style=\"font-family:Dokdo;font-size:30px;\">로그인하기</a>\r\n");
      out.write("\t\t</div>\t\t\r\n");

	}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).on(\"mouseenter\",\"a\",function(){\r\n");
      out.write("\t$(this).css('color', '#777777');\t\r\n");
      out.write("\t});\r\n");
      out.write("\t$(document).on(\"mousedown\",\"a\",function(){\r\n");
      out.write("\t\t$(this).css('color','#505050');\r\n");
      out.write("\t});\r\n");
      out.write("\t$(document).on(\"mouseleave\",\"a\",function(){\r\n");
      out.write("\t\t$(this).css('color','white');\r\n");
      out.write("\t});\r\n");
      out.write("\t$(document).on(\"mouseup\",\"a\",function(){\r\n");
      out.write("\t\t$(this).css('color','#777777');\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
